#version: '3.1'

services:
  api:
    image: microserviceobservabiliteuser
    ports:
     - 8080:8080
  db:
    image: mysql:8.0.39
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_user

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

volumes:
  dbbase:

rabbit:
  image: "rabbitmq:3-management"
  environment:
     RABBITMQ_ERLANG_COOKIE: "SWQOKODALRPCLNMEQG"
     RABBITMQ_DEFAULT_USER: "rabbitmq"
     RABBITMQ_DEFAULT_PASS: "rabbitmq"
     RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"
