#version: '3.1'

services:
  api:
    image: microserviceobservabiliteuser
    ports:
     - 8080:8080
  db:
    image: mysql:8.0.39
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_user

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

volumes:
  dbbase:
